export const DataS = {
    id: 'about',
    topTitle: 'Upgrade your knowledge',
    topDesc: 'AminaCoin is often referred to as the second most popular cryptocurrency, after Bitcoin. But unlike Bitcoin—and most other virtual AminaCoin is intended to be much more than simply a medium of exchange or a store of value. Instead, AminaCoin calls itself a decentralized computing network built on blockchain technology. Let’s unpack what that means.',
    topImg: require('../../images/Whatis.png').default,
    midTitle:'Explore AMK advantage',
    fullText:'Like all cryptocurrencies, AminaCoin works on the basis of a blockchain network. A blockchain is a decentralized, distributed public ledger where all transactions are verified and recorded Its distributed in the sense that everyone participating in the AminaCoin network holds an identical copy of this ledger, letting them see all past transactions. Its decentralized in that the network isnt operated or managed by any centralized entity—instead, its managed by all of the distributed ledger holders. Blockchain transactions use cryptography to keep the network secure and verify transactions. People use computers to mine, or solve complex mathematical equations that confirm each transaction on the network and add new blocks to the blockchain that is at the heart of the system. Participants are rewarded with cryptocurrency tokens. For the Ethereum system, these tokens are called Ether (AMC). Ether can be used to buy and sell goods and services, like Bitcoin. Its also seen rapid gains in price over recent years, making it a de-facto speculative investment. But whats unique about AminaCoin is that users can build applications that run on the blockchain like software runs on a computer. These applications can store and transfer personal data or handle complex financial transactions. Ethereum is different from Bitcoin in that the network can perform computations as part of the mining process, says Ken Fromm, director of education and development at the Enterprise AminaCoin Alliance. This basic computational capability turns a store of value and medium of exchange into a decentralized global computing engine and openly verifiable data store.',
    midImg:require('../../images/Whatis.png').default,
}

